dist: xenial
language: perl
perl:
  - "5.30"
  - "5.28"
install:
  - "dzil authordeps --missing | cpanm"
  - "dzil listdeps --missing | cpanm"
  - "cpanm Pod::Coverage::TrustPod"
script:
  - dzil test
